/** AUTH **/
export const LOGIN_ATTEMP = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_ATTEMP_FACEBOOK = 'LOGIN_ATTEMPT_FACEBOOK';
export const LOGIN_ATTEMP_GOOGLE = 'LOGIN_ATTEMP_GOOGLE';
export const LOGIN_ATTEMP_TWITTER = 'LOGIN_ATTEMP_TWITTER';

export const INVALID_SESSION = 'INVALID_SESSION';

export const REGISTER_ATTEMP = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

/** USER **/
export const USER_READ = 'USER_READ';
export const USER_READ_SUCCESS = 'USER_READ_SUCCESS';
export const USER_READ_FAILURE = 'USER_READ_FAILURE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR= 'USER_UPDATE_ERROR';
export const USER_LANGUAGE_REQUEST= 'USER_LANGUAGE_REQUEST';
export const USER_LANGUAGE_SUCCESS= 'USER_LANGUAGE_SUCCESS';
export const USER_LANGUAGE_FAILURE= 'USER_LANGUAGE_FAILURE';

/** IMAGE UPLOAD AND IMAGE FILE READ **/
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const IMAGE_UPLOAD_PROGRESS = 'IMAGE_UPLOAD_FAILURE';

export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';

export const IMAGE_READ = 'IMAGE_READ';
export const IMAGE_READ_PROGRESS = 'IMAGE_READ_FAILURE';
export const IMAGE_READ_FAILURE = 'IMAGE_READ_FAILURE';
export const IMAGE_READ_SUCCESS = 'IMAGE_READ_SUCCESS';

/*** TOKEN **/
export const TOKEN_API_CALL = 'TOKEN_API_CALL';
export const TOKEN_REFRESH = 'TOKEN_REFRESH';

/**** PUBLIC ***/


/*** PATIENTS **/
export const PATIENT_READ_REQUEST = 'PATIENT_REQUEST';
export const PATIENT_READ_SUCCESS = 'PATIENT_READ_SUCCESS';
export const PATIENT_READ_FAILURE = 'PATIENT_READ_FAILURE';
export const PATIENT_SELECTED = 'PATIENT_SELECTED';
export const PATIENT_SELECT = 'PATIENT_SELECT';
export const PATIENT_DISPLAY_DATA_FORM = 'PATIENT_DISPLAY_DATA_FORM';
export const PATIENT_HIDE_DATA_FORM = 'PATIENT_HIDE_DATA_FORM';
export const PATIENT_ADD_NEW_PATIENT = 'PATIENT_ADD_NEW_PATIENT';
export const PATIENT_SELECT_CANCELLED = 'PATIENT_SELECT_CANCELLED';

/*** DOCTORS ****/
export const DOCTOR_READ_REQUEST = 'DOCTOR_READ_REQUEST';
export const DOCTOR_READ_SUCCESS = 'DOCTOR_READ_SUCCESS';
export const DOCTOR_READ_FAILURE = 'DOCTOR_READ_FAILURE';
export const DOCTOR_SELECTED = 'DOCTOR_SELECTED';
export const DOCTOR_SELECT = 'DOCTOR_SELECT';

/*** APPOINTMENTS **/
export const APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST';
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';
export const APPOINTMENT_FAILURE = 'APPOINTMENT_FAILURE';
export const APPOINTMENT_SELECTED = 'APPOINTMENT_SELECTED';
export const APPOINTMENTS_READ_REQUEST = 'APPOINTMENTS_READ_REQUEST';
export const APPOINTMENTS_READ_SUCCESS = 'APPOINTMENTS_READ_SUCCESS';
export const APPOINTMENTS_READ_FAILURE = 'APPOINTMENTS_READ_FAILURE';
export const APPOINTMENT_NEW_DATE = 'APPOINTMENT_NEW_DATE';
